[package]
name = "scratch"
version = "0.1.4"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
crossterm = "0.29.0"
ratatui = "0.30.2"
tuimon = { git = "https://github.com/gabriele-rizzo/Tuimon.git", version = "0.1.0" }
ratatui-code-editor = { version = "0.0.6", features = ["crossterm"] }
ansi-to-tui = "8.0.1"
unicode-width = "0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2.189"
